const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const elements=new Map();
function el(id){if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',style:{},value:'',classList:{add(){},remove(){},toggle(){},contains(){return false;}},appendChild(){},insertAdjacentHTML(){},remove(){},addEventListener(){},parentElement:{appendChild(){}}});return elements.get(id);}
const c=vm.createContext({console,Math,Set,Map,JSON,Date,document:{getElementById:el,querySelector:el,querySelectorAll:()=>[],createElement:()=>el('new'),addEventListener(){}},window:{addEventListener(){},removeEventListener(){}},localStorage:{getItem(){return null;},setItem(){}},setTimeout:fn=>fn(),clearTimeout(){},setInterval(){},clearInterval(){},alert:msg=>{throw Error(msg);}});
const html=fs.readFileSync('index.html','utf8');
for(const m of html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))vm.runInContext(m[1],c);
vm.runInContext(fs.readFileSync('multi-battle.js','utf8'),c);
vm.runInContext(`
  function check(ok,msg){if(!ok)throw Error(msg);}
  for(const size of [2,3]){
    battleSize=size;mode='friend';
    const p=Array.from({length:size*2},()=>({sp:SP_BY_ID.duraludon,item:'none'}));
    startBattleWith(p,p.map((_,i)=>i),p,p.map((_,i)=>i));
    check(multiLiving('me').length===size,'active slots');
    check(multiBench('me').length===size,'bench');
    const old=multi.slots.me[0],next=multiBench('me')[0];
    multiSwitch({side:'me',mon:old,replacement:next},()=>{});
    check(multi.slots.me[0]===next&&!multiLiving('me').includes(old),'switch');
    const cover=multiLiving('me')[0],hidden=multiLiving('me')[1];
    multiSetBehind(hidden,cover);check(hidden.behindOf===cover&&!multiVisible('me').includes(hidden),'behind ally cannot be targeted');
    multiClearBehind(cover);check(!hidden.behindOf,'behind state clears with ally');
    const order=[];const realAttack=attack;attack=(a,d,m,img,cb)=>{order.push(a);cb();};
    multi.actions=['me','foe'].flatMap(side=>multiLiving(side).map((mon,i)=>{mon.base.spe=20+i+(side==='me'?30:0);return {side,mon,type:'move',move:M.thunderbolt,target:multiLiving(multiOther(side))[0]};}));
    multiResolve();
    check(order.length===size*2,'all slots act');
    check(order.every((m,i)=>i===0||effSpeed(order[i-1])>=effSpeed(m)),'speed order');
    attack=realAttack;
    // A real attack should resolve without a DOM or callback exception.
    const a=multiLiving('me')[0],d=multiLiving('foe')[0];me=a;foe=d;
    const hp=d.curHp;attack(a,d,M.thunderbolt,multiImage(d),()=>{});
    check(d.curHp<hp,'real damage');
    show('home');check(!multi,'leave battle');
  }
  const dura=makeMon(SP_BY_ID.duraludon,'none','p1'), fire=makeMon(SP_BY_ID.centiskorch,'none','cpu');
  me=dura;foe=fire;battleSize=1;
  const single=calcDamage(dura,fire,M.duraludonCannon,false);
  check(single.eff===1,'Duraludon cannon ignores type effectiveness');
  battleSize=2;const multiDmg=calcDamage(dura,fire,M.duraludonCannon,false).dmg;
  check(multiDmg>=Math.floor(single.dmg*1.49),'Duraludon cannon multi boost');
  const fairy=makeMon(SP_BY_ID.marilli,'none','cpu');
  check(M.duraludonDisaster.type==='dragon','Duraludon Disaster is Dragon type');
  check(M.duraludonDisaster.onceBattle&&M.duraludonDisaster.onceFlag==='usedDuraludonDisaster','Duraludon Disaster is once per battle');
  check(SP_BY_ID.empoleon!==undefined&&M.hydrocannon.power===120&&M.hydrocannon.trapTurns===3&&M.hydrocannon.trapDenom===10,'Empoleon Hydro Cannon and residual effect');
  battleSize=1;const intelSingle=makeMon(SP_BY_ID.inteleon,'none','p1');battleSize=2;const intelMulti=makeMon(SP_BY_ID.inteleon,'none','p1');
  check(intelSingle.base.spa===140&&intelMulti.base.spa===125&&intelSingle.base.spe===150,'Inteleon single and multi stats');
  intelSingle.isDynamax=true;intelSingle.isGigantamax=true;const gmaxSnipe=maxMoveFor(intelSingle,M.snipeshot);
  check(gmaxSnipe.name==='キョダイソゲキ'&&gmaxSnipe.power===140&&gmaxSnipe.ignoreAbility&&gmaxSnipe.forceCrit,'Inteleon G-Max Snipe Shot');
  const normalCrit=Object.assign({},intelSingle,{abilEff:null});
  check(calcDamage(intelSingle,fire,M.snipeshot,true).dmg>calcDamage(normalCrit,fire,M.snipeshot,true).dmg,'Sniper raises critical damage');
  const wool=makeMon(SP_BY_ID.dubwool,'none','p1'),woolPlain=Object.assign({},wool,{abilEff:null});
  check(wool.base.hp===100&&wool.base.def===100&&calcDamage(fire,wool,M.crunch,false).dmg<calcDamage(fire,woolPlain,M.crunch,false).dmg,'Dubwool Fluffy halves physical damage');
  const gengar=SPECIES[SP_BY_ID.gengar];
  check(gengar.types.includes('ghost')&&gengar.types.includes('poison')&&gengar.megas[0].base.spa===170&&gengar.megas[0].abil==='shadowtag','Gengar and Mega Gengar');
  const corviknight=SPECIES[SP_BY_ID.corviknight];
  check(corviknight.types.includes('flying')&&corviknight.types.includes('steel')&&corviknight.base.def===105&&corviknight.abil==='mirrorarmor','Corviknight');
  const thievul=SPECIES[SP_BY_ID.thievul];
  check(thievul.types[0]==='dark'&&thievul.base.spa===87&&thievul.base.spe===90&&thievul.abil==='unburden','Thievul');
  const obstagoon=SPECIES[SP_BY_ID.obstagoon];
  check(obstagoon.types.includes('dark')&&obstagoon.types.includes('normal')&&obstagoon.base.def===101&&obstagoon.abil==='defiant','Obstagoon');
  const drednaw=makeMon(SP_BY_ID.drednaw,'none','p1'),drednawPlain=Object.assign({},makeMon(SP_BY_ID.drednaw,'none','p1'),{abilEff:null});
  check(drednaw.types.includes('water')&&drednaw.types.includes('rock')&&drednaw.base.atk===115&&calcDamage(drednaw,fire,M.crunch,false).dmg>calcDamage(drednawPlain,fire,M.crunch,false).dmg,'Drednaw Strong Jaw');
  const hold=makeMon(SP_BY_ID.hold,'none','p1'),holdPlain=Object.assign({},makeMon(SP_BY_ID.hold,'none','p1'),{abilEff:null});
  check(hold.types.includes('normal')&&hold.types.includes('ground')&&calcDamage(hold,fire,M.earthquake,false).dmg>calcDamage(holdPlain,fire,M.earthquake,false).dmg,'Hold Huge Power');
  const galvantula=SPECIES[SP_BY_ID.galvantula];
  check(galvantula.types.includes('bug')&&galvantula.types.includes('electric')&&galvantula.base.spa===97&&galvantula.abil==='compoundeyes','Galvantula');
  const joltik=makeMon(SP_BY_ID.joltik,'eviolite','p1'),joltikPlain=makeMon(SP_BY_ID.joltik,'none','p1');
  check(joltik.base.hp===75&&joltik.base.def===75&&joltik.base.spd===75&&calcDamage(fire,joltik,M.fireblast,false).dmg<calcDamage(fire,joltikPlain,M.fireblast,false).dmg,'Boosted Joltik receives Eviolite bulk');
  const mamoswine=makeMon(SP_BY_ID.mamoswine,'none','p1'),mamoswinePlain=Object.assign({},makeMon(SP_BY_ID.mamoswine,'none','p1'),{abilEff:null});
  check(mamoswine.base.hp===110&&mamoswine.base.atk===130&&calcDamage(fire,mamoswine,M.fireblast,false).dmg<calcDamage(fire,mamoswinePlain,M.fireblast,false).dmg,'Mamoswine Thick Fat');
  check(calcDamage(dura,fairy,M.duraludonDisaster,false).eff===2,'Duraludon Disaster pierces Fairy immunity for 2x damage');
  const duraEviolite=makeMon(SP_BY_ID.duraludon,'eviolite','p1'),duraPlain=makeMon(SP_BY_ID.duraludon,'none','p1');
  check(calcDamage(fire,duraEviolite,M.fireblast,false).dmg<calcDamage(fire,duraPlain,M.fireblast,false).dmg,'Duraludon receives Eviolite bulk');
  hazards=emptyHazards();setHazard('foe','rocks',dura);setHazard('foe','rocks',dura);setHazard('foe','rocks',dura);
  check(hazards.foe.rocks===3,'Stealth Rock three layers');
  dura.duraludonShieldTurns=3;const shielded=calcDamage(fire,dura,M.fireblast,false).dmg;dura.duraludonShieldTurns=0;const plain=calcDamage(fire,dura,M.fireblast,false).dmg;
  check(shielded<=Math.ceil(plain*2/3),'Duraludon disaster shield');
  const cream=makeMon(SP_BY_ID.alcremie,'none','p1'),ally=makeMon(SP_BY_ID.duraludon,'none','p1'),enemy=makeMon(SP_BY_ID.centiskorch,'none','cpu');
  battleSize=2;me=cream;foe=enemy;ally.curHp=Math.floor(ally.maxHp*.4);
  attack(cream,ally,M.alcremieRecover,'myImg',()=>{});
  check(ally.curHp>Math.floor(ally.maxHp*.4),'Alcremie ally recovery');
  attack(cream,enemy,Object.assign({},M.magicalshine,{allyTarget:ally}),'foeImg',()=>{});
  check(ally.stages.atk===1&&ally.stages.spa===1,'Magical Shine decoration');
  cream.holeCakeTurns=3;ally.curHp=1;applyHoleCake([cream,ally]);
  check(ally.alcremieShieldHp===Math.floor(ally.maxHp*.25)&&ally.curHp>1,'Hole Cake ally shield and recovery');
`,c);
console.log('Double/triple, Duraludon and Alcremie features: battle actions, support, shields and hazards OK');
